name: Build, Sign, and Release XPI

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      EXT_ID: '{04d230ce-13df-4a51-a0ee-29789b5753e6}'
      ARTIFACTS_DIR: web-ext-artifacts
      SRC_DIR: src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Get version from manifest.json
        id: version
        run: |
          VERSION=$(jq -r .version $SRC_DIR/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get last version from update.json
        id: last_version
        run: |
          LAST_VERSION=$(jq -r ".[\"$EXT_ID\"].updates[0].version" update.json)
          echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV
          echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT

      - name: Check version bump
        run: |
          if [ "$VERSION" = "$LAST_VERSION" ]; then
            echo "Error: Version in manifest.json ($VERSION) has not changed from update.json ($LAST_VERSION). Please update manifest.json before running this workflow."
            exit 1
          fi

      - name: Lint extension
        run: web-ext lint --source-dir $SRC_DIR --self-hosted

      - name: Sign extension
        run: |
          rm -rf $ARTIFACTS_DIR
          web-ext sign \
            --api-key "${{ secrets.AMO_ISSUER }}" \
            --api-secret "${{ secrets.AMO_SECRET }}" \
            --source-dir $SRC_DIR \
            --artifacts-dir $ARTIFACTS_DIR \
            --channel unlisted

      - name: Find and rename signed XPI
        run: |
          XPI_NAME="temp-containers-plus-$VERSION.xpi"
          SIGNED_XPI=$(ls $ARTIFACTS_DIR/*.xpi)
          if [ ! -f "$SIGNED_XPI" ]; then
            echo "Signed XPI not found!"; exit 1;
          fi
          mv "$SIGNED_XPI" "$XPI_NAME"
          echo "XPI_NAME=$XPI_NAME" >> $GITHUB_ENV

      - name: Update update.json
        run: |
          RELEASE_NAME="v$VERSION"
          UPDATE_LINK="https://github.com/tam1m/open-temp-containers-plus/releases/download/$RELEASE_NAME/$XPI_NAME"
          jq --arg v "$VERSION" \
             --arg url "$UPDATE_LINK" \
             --arg id "$EXT_ID" \
             '.addons[$id].updates[0].version = $v | .addons[$id].updates[0].update_link = $url' \
             update.json > update.tmp && mv update.tmp update.json

      - name: Commit and push update.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Update update.json for $VERSION" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: ${{ env.XPI_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
